INSERT INTO noteful_folders (name)
VALUES
    ('Important'),
    ('Super'),
    ('Spangley');

INSERT INTO noteful_notes (name, folder_id, content)
VALUES
    ('Dogs', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna cursus eget nunc scelerisque. Egestas sed sed risus pretium quam. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Amet tellus cras adipiscing enim eu. Curabitur vitae nunc sed velit dignissim sodales ut. Convallis a cras semper auctor neque. Dignissim enim sit amet venenatis urna cursus eget nunc. Interdum velit laoreet id donec ultrices tincidunt. Nascetur ridiculus mus mauris vitae ultricies leo. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.'),
    ('Cats', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna cursus eget nunc scelerisque. Egestas sed sed risus pretium quam. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Amet tellus cras adipiscing enim eu. Curabitur vitae nunc sed velit dignissim sodales ut. Convallis a cras semper auctor neque. Dignissim enim sit amet venenatis urna cursus eget nunc. Interdum velit laoreet id donec ultrices tincidunt. Nascetur ridiculus mus mauris vitae ultricies leo. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.'),
    ('Pigs', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna cursus eget nunc scelerisque. Egestas sed sed risus pretium quam. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Amet tellus cras adipiscing enim eu. Curabitur vitae nunc sed velit dignissim sodales ut. Convallis a cras semper auctor neque. Dignissim enim sit amet venenatis urna cursus eget nunc. Interdum velit laoreet id donec ultrices tincidunt. Nascetur ridiculus mus mauris vitae ultricies leo. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.'),
    ('Birds', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna cursus eget nunc scelerisque. Egestas sed sed risus pretium quam. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Amet tellus cras adipiscing enim eu. Curabitur vitae nunc sed velit dignissim sodales ut. Convallis a cras semper auctor neque. Dignissim enim sit amet venenatis urna cursus eget nunc. Interdum velit laoreet id donec ultrices tincidunt. Nascetur ridiculus mus mauris vitae ultricies leo. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.'),
    ('Bears', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna cursus eget nunc scelerisque. Egestas sed sed risus pretium quam. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Amet tellus cras adipiscing enim eu. Curabitur vitae nunc sed velit dignissim sodales ut. Convallis a cras semper auctor neque. Dignissim enim sit amet venenatis urna cursus eget nunc. Interdum velit laoreet id donec ultrices tincidunt. Nascetur ridiculus mus mauris vitae ultricies leo. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.'),
    ('Horses', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna cursus eget nunc scelerisque. Egestas sed sed risus pretium quam. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Amet tellus cras adipiscing enim eu. Curabitur vitae nunc sed velit dignissim sodales ut. Convallis a cras semper auctor neque. Dignissim enim sit amet venenatis urna cursus eget nunc. Interdum velit laoreet id donec ultrices tincidunt. Nascetur ridiculus mus mauris vitae ultricies leo. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.'),
    ('Tigers', 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna cursus eget nunc scelerisque. Egestas sed sed risus pretium quam. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Amet tellus cras adipiscing enim eu. Curabitur vitae nunc sed velit dignissim sodales ut. Convallis a cras semper auctor neque. Dignissim enim sit amet venenatis urna cursus eget nunc. Interdum velit laoreet id donec ultrices tincidunt. Nascetur ridiculus mus mauris vitae ultricies leo. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.'),
    ('Wolves', 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna cursus eget nunc scelerisque. Egestas sed sed risus pretium quam. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Amet tellus cras adipiscing enim eu. Curabitur vitae nunc sed velit dignissim sodales ut. Convallis a cras semper auctor neque. Dignissim enim sit amet venenatis urna cursus eget nunc. Interdum velit laoreet id donec ultrices tincidunt. Nascetur ridiculus mus mauris vitae ultricies leo. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.'),
    ('Elephants', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna cursus eget nunc scelerisque. Egestas sed sed risus pretium quam. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Amet tellus cras adipiscing enim eu. Curabitur vitae nunc sed velit dignissim sodales ut. Convallis a cras semper auctor neque. Dignissim enim sit amet venenatis urna cursus eget nunc. Interdum velit laoreet id donec ultrices tincidunt. Nascetur ridiculus mus mauris vitae ultricies leo. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.'),
    ('Lions', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna cursus eget nunc scelerisque. Egestas sed sed risus pretium quam. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Amet tellus cras adipiscing enim eu. Curabitur vitae nunc sed velit dignissim sodales ut. Convallis a cras semper auctor neque. Dignissim enim sit amet venenatis urna cursus eget nunc. Interdum velit laoreet id donec ultrices tincidunt. Nascetur ridiculus mus mauris vitae ultricies leo. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.'),
    ('Monkeys', 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna cursus eget nunc scelerisque. Egestas sed sed risus pretium quam. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Amet tellus cras adipiscing enim eu. Curabitur vitae nunc sed velit dignissim sodales ut. Convallis a cras semper auctor neque. Dignissim enim sit amet venenatis urna cursus eget nunc. Interdum velit laoreet id donec ultrices tincidunt. Nascetur ridiculus mus mauris vitae ultricies leo. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.'),
    ('Bats', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna cursus eget nunc scelerisque. Egestas sed sed risus pretium quam. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Amet tellus cras adipiscing enim eu. Curabitur vitae nunc sed velit dignissim sodales ut. Convallis a cras semper auctor neque. Dignissim enim sit amet venenatis urna cursus eget nunc. Interdum velit laoreet id donec ultrices tincidunt. Nascetur ridiculus mus mauris vitae ultricies leo. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.'),
    ('Turtles', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna cursus eget nunc scelerisque. Egestas sed sed risus pretium quam. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Amet tellus cras adipiscing enim eu. Curabitur vitae nunc sed velit dignissim sodales ut. Convallis a cras semper auctor neque. Dignissim enim sit amet venenatis urna cursus eget nunc. Interdum velit laoreet id donec ultrices tincidunt. Nascetur ridiculus mus mauris vitae ultricies leo. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.'),
    ('Zebras', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna cursus eget nunc scelerisque. Egestas sed sed risus pretium quam. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Amet tellus cras adipiscing enim eu. Curabitur vitae nunc sed velit dignissim sodales ut. Convallis a cras semper auctor neque. Dignissim enim sit amet venenatis urna cursus eget nunc. Interdum velit laoreet id donec ultrices tincidunt. Nascetur ridiculus mus mauris vitae ultricies leo. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.');
